"use client"
import Head from 'next/head'

import Header from '../components/header'
import Presentation from '../components/presentation';
import React, { useRef } from "react";


export default function Home() {
  return (
    <>
      <Head>
        <title>Bouziane Nassim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <img
        src="/photo.jfif"
        alt="A Image of me"
        className="border rounded-[20px] sticky top-[20%] left-[82%] mt-7"
      ></img> 
      <Presentation />
    </>
  )
}
