"use client"
import Head from 'next/head'

import Header from '../components/header'
import Presentation from '../components/presentation';
import React, { useRef } from "react";


export default function Home() {
  return (
    <>
      <Head>
        <title>Bouziane Nassim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />     
        <style> @import url('https://fonts.googleapis.com/css2?family=Open+Sans:ital@1&display=swap'); </style>
      </Head>
      <Header />
      <Presentation />
    </>
  )
}
