"use client"
import Head from 'next/head'

import Header from '../components/header'
import Presentation from '../components/presentation';
import APropos from '../components/APropos';
import React, { useRef } from "react";


export default function Home() {
  return (
    <>
      <Head>
        <title>Bouziane Nassim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet"/>
      </Head>
      <Header />
      <Presentation />
      <APropos/>
    </>
  )
}
