'use client';

import Head from 'next/head';

import React from 'react';
import ScrollToTop from 'react-scroll-to-top';
import Header from '../components/header';
import Presentation from '../components/presentation';
import WorkExperience from '../components/WorkExperience';
import Education from '../components/Education';
import Competence from '../components/Competence';
import PersonnalProject from '../components/PersonnalProject';
import Footer from '../components/footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Nassim BOUZIANE - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />

        <link
          href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap"
          rel="stylesheet"
        />

      </Head>
      <ScrollToTop style={{ right: '60px' }} smooth top={300} component={<img src="Logo.png"></img>} />
      <Header />
      <Presentation />
      <WorkExperience />
      <Education />
      <Competence />
      <PersonnalProject />
      <Footer />
    </>
  );
}
