"use client";
import Head from "next/head";

import Header from "../components/header";
import Presentation from "../components/presentation";
import APropos from "../components/APropos";
import React, { useEffect, useRef } from "react";
import Competences from "../components/competences";
import Mesprojets from "../components/mesprojets";
import Footer from "../components/footer";
import ScrollToTop from "react-scroll-to-top";


export default function Home() {
  useEffect(() => {
    // Met à jour le titre du document
    document.title = ` Nassim BOUZIANE - Portfolio`;
  }, []);
  return (
    <>
      <Head>
        <title>Bouziane Nassim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />

        <link
          href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap"
          rel="stylesheet"
        />
        
      </Head>
      <ScrollToTop style={{right:'60px'}} smooth top={300} component={<img src="Logo.png"></img>} />
      <Header />
      <Presentation />
      <APropos />
      <Competences />
      <Mesprojets />
      <Footer />
    </>
  );
}
